// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.xraycare.Database;

#nullable disable

namespace api.xraycare.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260216000000_AddScheduleConfigs")]
    partial class AddScheduleConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("db.xraycare.Machine", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RID"));
                    b.Property<string>("Machine_name").HasColumnType("text");
                    b.Property<string>("Room").HasColumnType("text");
                    b.Property<string>("Register_date").HasColumnType("text");
                    b.Property<string>("Caretaker").HasColumnType("text");
                    b.HasKey("RID");
                    b.ToTable("Machines");
                });

            modelBuilder.Entity("db.xraycare.UserAccount", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RID"));
                    b.Property<string>("Username").HasColumnType("text");
                    b.Property<string>("Password").HasColumnType("text");
                    b.Property<string>("Position").HasColumnType("text");
                    b.HasKey("RID");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("db.xraycare.RepairRequest", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RID"));
                    b.Property<string>("Equipment").HasColumnType("text");
                    b.Property<string>("Room").HasColumnType("text");
                    b.Property<string>("RequestDate").HasColumnType("text");
                    b.Property<string>("Detail").HasColumnType("text");
                    b.Property<string>("Remarks").HasColumnType("text");
                    b.Property<string>("StatusText").HasColumnType("text");
                    b.Property<string>("ImageData").HasColumnType("text");
                    b.HasKey("RID");
                    b.ToTable("RepairRequests");
                });

            modelBuilder.Entity("db.xraycare.ChecklistRecord", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RID"));
                    b.Property<string>("FormType").HasColumnType("text");
                    b.Property<string>("MachineName").HasColumnType("text");
                    b.Property<string>("Room").HasColumnType("text");
                    b.Property<string>("CheckDate").HasColumnType("text");
                    b.Property<string>("Tester").HasColumnType("text");
                    b.Property<string>("JsonData").HasColumnType("text");
                    b.HasKey("RID");
                    b.ToTable("ChecklistRecords");
                });

            modelBuilder.Entity("db.xraycare.ScheduleConfig", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RID"));
                    b.Property<string>("StartDate").HasColumnType("text");
                    b.Property<string>("FrequencyType").HasColumnType("text");
                    b.Property<string>("Description").HasColumnType("text");
                    b.HasKey("RID");
                    b.ToTable("ScheduleConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
