@api.xraycare_HostAddress = http://localhost:8001

### GET all machines
GET {{api.xraycare_HostAddress}}/api/Xraycare/GetAllMachines
Accept: application/json

### POST add machine
POST {{api.xraycare_HostAddress}}/api/Xraycare/AddMachine
Content-Type: application/json

{
  "machineName": "X-Ray (BrandA/ModelX)",
  "room": "2",
  "registerDate": "25/11/2025",
  "caretaker": "ศุภกร งามเมือง"
}

###
